Private Sub Workbook_Open()
    ThisWorkbook.Activate
    Dim clsR As clsResponsive
    Set clsR = New clsResponsive
    Call clsR.responsive
    Set clsR = Nothing
End Sub

Private Sub Workbook_SheetActivate(ByVal Sh As Object)
    ThisWorkbook.Activate
    Dim clsR As clsResponsive
    Set clsR = New clsResponsive
    Call clsR.responsive
    Set clsR = Nothing
End Sub

Private Sub Workbook_WindowResize(ByVal Wn As Window)
    ThisWorkbook.Activate
    Dim clsR As clsResponsive
    Set clsR = New clsResponsive
    Call clsR.responsive
    Set clsR = Nothing
End Sub
